backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

locale: "el"

collections:
  - name: "portfolio"
    label: "Φωτογραφίες"
    folder: "img/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Τίτλος", name: "title", widget: "string" }
      - { label: "Εικόνα", name: "image", widget: "image" }
